import { Attachment } from "../../../max-messaging/services/mail/types";

export type MailAccount = {
  attachments?: Attachment[];
  subject?: string;
  email: string;
  firstName?: string;
  lastName?: string;
  fullName?: string;
  companyName?: string;
  invitationLink?: string;
  individualName?: string;
  invitationCode?: string;
  companyEmployeeName?: string;
  projectName?: string;
  clientName?: string;
  invoiceNumber?: string;
  taskName?: string;
  taskDescription?: string;
  taskDueDate?: string;
  role?: string;
  context?: string;
  currency?: string;
  amount?: number;
  otp?: string;
  currencyCode?: string;
  timeLeft?: string;
  planName?: string;
  seatsUsed?: number;
  supportUrl?: string;
  accountUrl?: string;
  updatePaymentMethodUrl?: string;
  manageSubscriptionUrl?: string;
  paymentAttemptDate?: string;
  paymentDate?: string;
  customerName?: string;
  trialEnd?: string;
  price?: number;
  billingCycle?: string;
  nextBillingDate?: string;
  invoiceUrl?: string;
  accessUntilDate?: string;
  cancelledDate?: string;
  reactivateSubscriptionUrl?: string;
  notificationType?: {
    first: boolean;
    second: boolean;
    final: boolean;
  };
  isPaid?:
    | boolean
    | {
        amount: number;
        nextBillingDate: string;
        billingCycle: string;
        cardType: string;
        cardLastFourDigits: string;
      };
  cardType?: string;
  cardLastFourDigits?: string;
  previousQuantity?: number;
  newQuantity?: number;
  newBillingAmount?: number;
  effectiveDate?: string;
  newPlanName?: string;
  oldPlanName?: string;
  submissionDate?: string;
  dashboardUrl?: string;
  approvalDate?: string;
  accountName?: string;
  accountNumber?: string;
  bankName?: string;
  declinedReason?: string;
  newRequestUrl?: string;
};
